### PR TITLE
Made all data User based

### LINKED ISSUE #48: Make everything based around a User
So that the data can be changed from user to user, make all of the content from the fridge and grocery list page content that is received from a User.

### PR DESCRIPTION
**Pull request by Kee-Sharp**

### CODE REVIEW

**Review by ToriKraj — APPROVED** [review]
This is really cool and awesome! I'm wondering if we will get criticized for having the switch user button on the fridge page instead of the user profile page, but I'm not sure this overly matters. Great work!

**Comment by Kee-Sharp** [comment]
> This is really cool and awesome! I'm wondering if we will get criticized for having the switch user button on the fridge page instead of the user profile page, but I'm not sure this overly matters. Great work!

I was about to go change it really quickly but yea it won't be in the final version anyway and plus the user page has 2 buttons kind of like this already.

**Comment by ToriKraj** [comment]
Valid!

**Review by M-Bisson — APPROVED** [review]
Good to go

**Pull request merged**
